let products=[], category=null, currency=localStorage.getItem("xe_currency")||"MXN", selected=null, pay=null;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const physical=["Herramientas","Insumos"];
fetch("data/productos.json").then(r=>r.json()).then(d=>{products=d.filter(p=>p.estado!=="inactivo"); syncCurrency();});
function syncCurrency(){ $$("[data-cur]").forEach(b=>b.classList.toggle("active",b.dataset.cur===currency)); }
$$("[data-cur]").forEach(b=>b.onclick=()=>{ if(category&&physical.includes(category))return; currency=b.dataset.cur;localStorage.setItem("xe_currency",currency);syncCurrency();if(category)render();});
$$("[data-cat]").forEach(b=>b.onclick=()=>openCategory(b.dataset.cat));
function openCategory(cat){category=cat;if(physical.includes(cat)){currency="MXN";syncCurrency()}$("#categories").classList.add("hidden");$("#catalog").classList.remove("hidden");$("#catTitle").textContent=cat;$("#notice").textContent=physical.includes(cat)?"Venta únicamente en México. Los gastos de envío corren por cuenta del cliente.":cat==="Proyectos XE"?"Contenido técnico digital: información de fabricación, lista de materiales y código para construir el proyecto. No se envía un dispositivo físico.":"Productos digitales disponibles para México y otros países.";render()}
$("#back").onclick=()=>{$("#catalog").classList.add("hidden");$("#categories").classList.remove("hidden");category=null;$("#search").value=""}
$("#search").oninput=()=>{if(!category){let q=$("#search").value.trim().toLowerCase();if(q){let hit=products.find(p=>(p.nombre+" "+p.consola+" "+p.categoria).toLowerCase().includes(q));if(hit)openCategory(normalize(hit));}}else render()}
function normalize(p){let c=(p.consola||"").toLowerCase();if(c==="ps4")return"PS4";if(c==="ps5")return"PS5";if(c.includes("series s"))return"Xbox Series S";if(c.includes("series x"))return"Xbox Series X";if(c.includes("xbox one"))return"Xbox One";if(c.includes("nintendo"))return"Nintendo";return p.consola}
function belongs(p){return normalize(p)===category || p.categoria===category || (category==="Proyectos XE"&&(p.categoria==="Proyecto"||p.categoria==="Proyectos XE"))}
function render(){let q=$("#search").value.toLowerCase().trim();let list=products.filter(p=>belongs(p)&&(!q||(p.nombre+" "+p.descripcion+" "+p.id).toLowerCase().includes(q)));$("#products").innerHTML=list.length?list.map(p=>`<article class="card"><img src="${p.imagen}" alt="${esc(p.nombre)}" loading="lazy"><div class="card-body"><span class="badge">${esc(p.categoria)} · ${esc(p.id)}</span><h3>${esc(p.nombre)}</h3><p class="desc">${esc(p.descripcion||"Recurso técnico XE.")}</p><p class="price">$${currency==="MXN"?p.precioMXN:p.precioUSD} ${currency}</p><button class="buy" data-buy="${esc(p.id)}">COMPRAR</button></div></article>`).join(""):`<div class="empty"><h3>PRÓXIMAMENTE</h3><p>Aún no hay productos publicados en esta zona.</p></div>`;$$("[data-buy]").forEach(b=>b.onclick=()=>openBuy(b.dataset.buy))}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function openBuy(id){selected=products.find(p=>p.id===id);pay=null;$("#summary").innerHTML=`<div class="order"><img src="${selected.imagen}"><div><span class="badge">${esc(selected.id)}</span><h2>${esc(selected.nombre)}</h2><b class="price">$${currency==="MXN"?selected.precioMXN:selected.precioUSD} ${currency}</b></div></div>`;$("#payInfo").innerHTML="<p>Selecciona un método de pago para ver las instrucciones.</p>";$$("[data-pay]").forEach(b=>b.classList.remove("active"));$("#send").disabled=true;$("#send").textContent="SELECCIONA UN MÉTODO DE PAGO";$("#modal").classList.remove("hidden")}
$("#close").onclick=()=>$("#modal").classList.add("hidden");$("#modal").onclick=e=>{if(e.target===$("#modal"))$("#modal").classList.add("hidden")}
$$("[data-pay]").forEach(b=>b.onclick=()=>{pay=b.dataset.pay;$$("[data-pay]").forEach(x=>x.classList.toggle("active",x===b));if(pay==="paypal"){$("#payInfo").innerHTML="<b>Pago mediante PayPal</b><p>Escribe tu correo electrónico y solicita el link de pago correspondiente al artículo seleccionado.</p>";$("#send").textContent="SOLICITAR LINK DE PAGO"}else{let p=XE_CONFIG.payments[pay];$("#payInfo").innerHTML=`<b>${p.label}</b><br>${p.detail}<br><small>${p.accountLabel||"Tarjeta / cuenta"}</small><br><strong>${p.account}</strong><br>Titular: ${p.holder}<p>Una vez realizado el pago, envía tu comprobante para validar tu compra y recibir tu producto.</p>`;$("#send").textContent="ENVIAR COMPROBANTE POR WHATSAPP"}$("#send").disabled=false})
$("#send").onclick=()=>{let name=$("#clientName").value.trim(),email=$("#clientEmail").value.trim();if(!name||!email){alert("Escribe tu nombre y correo electrónico.");return}let price=`$${currency==="MXN"?selected.precioMXN:selected.precioUSD} ${currency}`;let msg=pay==="paypal"?`💳 SOLICITUD DE LINK DE PAGO PAYPAL\n\nProducto: ${selected.nombre}\nID: ${selected.id}\nPrecio: ${price}\n\nNombre del cliente: ${name}\nCorreo electrónico: ${email}\n\nSolicito el link de pago PayPal correspondiente al artículo seleccionado.`:`🛒 NUEVA COMPRA - XE SERVICIO ELECTRÓNICO\n\nProducto: ${selected.nombre}\nID: ${selected.id}\nPrecio: ${price}\n\nMétodo de pago: ${XE_CONFIG.payments[pay].label}\nNombre del cliente: ${name}\nCorreo electrónico: ${email}\n\nYa realicé el pago. Adjunto mi comprobante de transferencia o depósito.`;window.open(`https://api.whatsapp.com/send?phone=${XE_CONFIG.whatsappNumber}&text=${encodeURIComponent(msg)}`,"_blank")}
